{{- $deployment := .Values.crmngx -}}
{{- $deploymentName := printf "%s-%s" .Release.Name $deployment.name }}

{{- $crmDevSvcName := printf "%s-%s" .Release.Name .Values.crmdev.name}}
{{- $crmSdkSvcName := printf "%s-%s" .Release.Name .Values.crmsdk.name}}
{{- $crmParentSvcName := printf "%s-%s" .Release.Name .Values.crmparent.name}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $deploymentName }}-configmap
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
    role: {{ $deployment.role }}
  annotations: 
    released: {{ .Release.Time}}       
data:
  {{ .Values.ingress.hostname }}.conf: |
      server {
        server_name {{ .Values.ingress.hostname }};
        listen 8080 default_server;

        location = /_healthz {
          add_header Content-Type text/plain;
          return 200 'ok';
        }
        # store
        location /integration/demo/parent {
            rewrite ^/integration/demo/parent/(.*)$ /$1 break;
            proxy_pass http://{{ $crmParentSvcName }}:8080;
        }
        location /integration/game/iframe {
            proxy_pass http://{{ $crmParentSvcName }}:8080;
        }
        location /integration/game/billing {
            proxy_pass http://{{ $crmParentSvcName }}:8080;
        }

        # gamenet provider
        location /integration/demo/dev {
            rewrite ^/integration/demo/dev/(.*)$ /$1 break;
            proxy_pass http://{{ $crmDevSvcName }}:8080;
        }

        # qilin hub
        location /integration/demo/qilin {
            rewrite ^/integration/demo/qilin/(.*)$ /$1 break;
            proxy_pass http://{{ $crmSdkSvcName }}:8080;
        }

      }
      server {
        server_name {{ .Values.ingressProxy.hostname }};
        listen 8080;
        
        location / {
            proxy_pass http://{{ $crmDevSvcName }}:1443;
        }
      }
      server {
        server_name {{ .Values.ingressStore.hostname }};
        listen 8080;
        
        location /v1/rambler {
            proxy_pass http://{{ $crmParentSvcName }}:8080/payment/v1/rambler;
        }

        location /api {
            proxy_pass http://{{ $crmParentSvcName }}:8082;
        }

        # not for production ( separate internal nginx server)
        location /internal {
            proxy_pass http://{{ $crmParentSvcName }}:8082;
        }

        location / {
            proxy_pass http://qilin-store-ui:80;
        }
      }
