{{- $deployment := .Values.crmsdk -}}
{{- $deploymentName := printf "%s-%s" .Release.Name $deployment.name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
  annotations:
    released: {{ .Release.Time}}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: {{ $deployment.role }}
  replicas: {{ $deployment.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: {{ $deployment.role }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
      - name: {{ $deployment.name }}-db-migrate
        image: {{ .Values.backend.image }}:{{ .Values.backend.imageTag }}
        args: ["migrate","up","--dsn","${APP_POSTGRES_DSN}"]
        env:
        - name: APP_POSTGRES_DSN
          valueFrom:
            secretKeyRef:
              name: {{ $deploymentName }}-env
              key: APP_POSTGRES_DSN
      containers:
        - name: {{ $deployment.name }}
          image: {{ .Values.backend.image }}:{{ .Values.backend.imageTag }}
          args: ["sdk","-c","configs/sdk.yaml","-b",":8080"]
          ports:
            {{- range $port := $deployment.ports }}
            - containerPort: {{ $port.port }}
            {{- end }}
          env:
            {{- range $deployment.env }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $deploymentName }}-env
                  key: {{ . }}
            {{- end }}
          #livenessProbe:
          #  httpGet:
          #    path: /health
          #    port: {{ $deployment.healthPort }}
          #  initialDelaySeconds: 15
          #  timeoutSeconds: 1
          #  failureThreshold: 3
          #  periodSeconds: 5
          #volumeMounts:
          #- name: {{ $deploymentName }}-config
          #  mountPath: /application/etc/
          #  readOnly: tru
