schema:
  - "api/graphql/*.graphql"

exec:
  filename: internal/generated/graphql/generated.go

model:
  filename: internal/generated/graphql/models_gen.go

resolver:
  filename: internal/resolver/resolver_gen.go
  type: Resolver