graphql:
  introspection: true
  dataloader:
    wait: 250us
  playground:
    route: /client
    name: local
    endpoint: /v1/graphql
postgres:
  dsn: postgres://qilin:insecure@localhost:5567/qilin?sslmode=disable
  maxOpenConns: 5
  maxIdleConns: 3
  connMaxLifetime: 15m
  logLevel: debug
dispatcher:
  cors:
    allowed:
      - "http://localhost:3000"
    methods:
      - "HEAD"
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
    headers:
      - "*"
  auth:
    oauth2:
      clientId: "5da4ec412b13220001efe179"
      clientSecret: "w9JkFlYOa7Hr6QY4OwMv4CWUl3rkJJkwkBjEdkGFE6SQILaM3Hpzxsvs5REdMFNV"
      redirectUrl: "http://localhost:8082/auth/v1/callback"
    secret: secretkey
    successRedirectURL: http://localhost:3000/auth_success
    jwt:
      publicKey: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJdLA2Q1fMTdr6a1mg3oCjwxJnj6w
        i5eiweQa2c7oBqF0RIrsNzAepS47rxHaOQl7REVI1btuJ+fITxhGY5r2wA==
        -----END PUBLIC KEY-----


      privateKey: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIDgMLiKqAZ1l3sNvFTXph9opUsoijGqItCUP8K6lLp9KoAoGCCqGSM49
        AwEHoUQDQgAEJdLA2Q1fMTdr6a1mg3oCjwxJnj6wi5eiweQa2c7oBqF0RIrsNzAe
        pS47rxHaOQl7REVI1btuJ+fITxhGY5r2wA==
        -----END EC PRIVATE KEY-----      


webhooks:
  secret: insecure
