metric:
  statsD:
    addr: 127.0.0.1:8125
    prefix: stats
    flushInterval: 100ms
    flushBytes: 1440
    options:
      sampleRate: 1.0
  scope:
    prefix: qilin
    tags:
      service: qilin
  interval: 1s
tracing:
  disabled: true
  serviceName: qilin
graphql:
  introspection: true
  dataloader:
    wait: 250us
  playground:
    route: /client
    name: local
    endpoint: /query
  route: /query
postgres:
  dsn: postgres://qilin:insecure@localhost:5567/qilin?sslmode=disable
  maxOpenConns: 5
  maxIdleConns: 3
  connMaxLifetime: 15m
  logLevel: debug
dispatcher:
  cors:
    allowed:
      - "*"
    methods:
      - "HEAD"
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
    headers:
      - "*"
  oauth:
    clientId: "unknown"
    clientSecret: "unknown"
    redirectUrl: "unknown"
    group: "/auth"
    routes:
      auth: "/"
      callback: "/callback"
      logout: "/logout"