graphql:
  introspection: true
  dataloader:
    wait: 250us
  playground:
    route: /client
    name: local
    endpoint: /v1/graphql
postgres:
  dsn: postgres://qilin:insecure@localhost:5567/qilin?sslmode=disable
  maxOpenConns: 5
  maxIdleConns: 3
  connMaxLifetime: 15m
  logLevel: debug
dispatcher:
  cors:
    allowed:
      - "*"
    methods:
      - "HEAD"
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
    headers:
      - "*"
  oauth:
    clientId: "unknown"
    clientSecret: "unknown"
    redirectUrl: "unknown"
    group: "/auth"
    routes:
      auth: "/"
      callback: "/callback"
      logout: "/logout"
webhooks:
  secret: insecure