graphql:
  introspection: true
  dataloader:
    wait: 250us
  playground:
    route: /client
    name: local
    endpoint: /v1/graphql
postgres:
  dsn: postgres://qilin:insecure@localhost:5567/qilin?sslmode=disable
  maxOpenConns: 5
  maxIdleConns: 3
  connMaxLifetime: 15m
  logLevel: debug
dispatcher:
  cors:
    allowed:
      - "http://localhost:3000"
    methods:
      - "HEAD"
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
    headers:
      - "*"
  auth:
    oauth2:
      clientId: "5da4ec412b13220001efe179"
      clientSecret: "w9JkFlYOa7Hr6QY4OwMv4CWUl3rkJJkwkBjEdkGFE6SQILaM3Hpzxsvs5REdMFNV"
      redirectUrl: "http://localhost:8082/auth/v1/callback"
    secret: secretkey
    successRedirectURL: http://localhost:3000/auth_success
webhooks:
  secret: insecure
