stan:
  stanClusterId: "test-cluster"
  stanClientId: "qilin-mailer"
  stanOptions:
    natsURL: nats://natss:4222
eventbus:
  enabled: true
  subjects:
    invitesOut: "invites"
    invitesIn: "invites"
  subscribers:
    - "invites"
mailer:
  subject: "You have new invite"
  template: "configs/mail/new_invite.tpl"
  MaxAttempts: 5
  clientOptions:
    host: "localhost"
    port: 25
    username: ""
    password: ""
    replyTo: ""
    from: ""
    insecureSkipVerify: true