protoc:
  version: 3.9.1

generate:
  go_options:
    import_path: github.com/qilin/crm-api

  plugins:
    - name: go
      type: go
      flags: plugins=grpc
      output: generated

    - name: micro
      type: go
      flags: plugins=grpc
      output: generated