graphql:
  introspection: true
  dataloader:
    wait: 250us
  playground:
    route: /client
    name: local
    endpoint: /v1/graphql
postgres:
  dsn: postgres://postgres:postgres@localhost:5567/qilin-hasura?sslmode=disable
  maxOpenConns: 5
  maxIdleConns: 3
  connMaxLifetime: 15m
  logLevel: debug
dispatcher:
  cors:
    allowed:
      - "*"
    methods:
      - "HEAD"
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
    headers:
      - "*"
sdk:
  mode: "parent"
  plugins:
    - plugins/rambler.so
  pluginsConfig:
    parent_iframe_url: "https://tst.qilin.super.com/integration/demo/qilin/sdk/v1/iframe"
    # parent_iframe_url: "http://localhost:8086/sdk/v1/iframe"
    parent_iframe_route: "/game"
    parent_iframe_template: "configs/sdk/parent-index.html"
    parent_index_route: "/store"
    parent_index_template: "configs/sdk/store.html"
    parent_app_secret: "rambler's app secret key"
    parent_auth_cookie_name: "qpssid"
    parent_public_key: |
      -----BEGIN PUBLIC KEY-----
      MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEfQa/uwg5YlO8DTa98hwwt795y4F3ST4A
      T1/2WtQTdggoYIzdgNTgQ7lX9+ZLjorowANuooooeuO+51Sw1hZTKbtEa7oOHxr+
      o78UMCziRQeQzRBnIBjHt8Z2H9DUxrHb
      -----END PUBLIC KEY-----

    parent_private_key: |
      -----BEGIN PRIVATE KEY-----
      MIGkAgEBBDAEk3lnN3fagRuoi7SZnpiq6+KW9uU7OLgfvONA+gTzToFWYel8qW3L
      4PFpjFPb0MmgBwYFK4EEACKhZANiAAR9Br+7CDliU7wNNr3yHDC3v3nLgXdJPgBP
      X/Za1BN2CChgjN2A1OBDuVf35kuOiujAA26iiih6477nVLDWFlMpu0Rrug4fGv6j
      vxQwLOJFB5DNEGcgGMe3xnYf0NTGsds=
      -----END PRIVATE KEY-----
  jwt:
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEfQa/uwg5YlO8DTa98hwwt795y4F3ST4A
      T1/2WtQTdggoYIzdgNTgQ7lX9+ZLjorowANuooooeuO+51Sw1hZTKbtEa7oOHxr+
      o78UMCziRQeQzRBnIBjHt8Z2H9DUxrHb
      -----END PUBLIC KEY-----

    privateKey: |
      -----BEGIN PRIVATE KEY-----
      MIGkAgEBBDAEk3lnN3fagRuoi7SZnpiq6+KW9uU7OLgfvONA+gTzToFWYel8qW3L
      4PFpjFPb0MmgBwYFK4EEACKhZANiAAR9Br+7CDliU7wNNr3yHDC3v3nLgXdJPgBP
      X/Za1BN2CChgjN2A1OBDuVf35kuOiujAA26iiih6477nVLDWFlMpu0Rrug4fGv6j
      vxQwLOJFB5DNEGcgGMe3xnYf0NTGsds=
      -----END PRIVATE KEY-----

    subject: "QilinSubject"
    iss: "Qilin"
    exp: 6000