graphql:
  introspection: true
  dataloader:
    wait: 250us
  playground:
    route: /client
    name: local
    endpoint: /v1/graphql
postgres:
  dsn: postgres://qilin:insecure@localhost:5567/qilin-hasura?sslmode=disable
  maxOpenConns: 5
  maxIdleConns: 3
  connMaxLifetime: 15m
  logLevel: debug
dispatcher:
  cors:
    allowed:
      - "*"
    methods:
      - "HEAD"
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
    headers:
      - "*"
      -
sdk:
  mode:
  plugins:
    - test/testdata/plugins/so/plugin.so
  jwt:
    publicKey: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEVs/o5+uQbTjL3chynL4wXgUg2R9
      q9UU8I5mEovUf86QZ7kOBIjJwqnzD1omageEHWwHdBO6B+dFabmdT9POxg==
      -----END PUBLIC KEY-----

    privateKey: |
      -----BEGIN PRIVATE KEY-----
      MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgevZzL1gdAFr88hb2
      OF/2NxApJCzGCEDdfSp6VQO30hyhRANCAAQRWz+jn65BtOMvdyHKcvjBeBSDZH2r
      1RTwjmYSi9R/zpBnuQ4EiMnCqfMPWiZqB4QdbAd0E7oH50VpuZ1P087G
      -----END PRIVATE KEY-----
    iss: "Qilin"
    exp: 6000