version: '3.7'
services:
  crm-migration:
    command: ["migrate","up","--dsn","postgres://qilin:insecure@postgres:5432/qilin?sslmode=disable"]
  crm-daemon:
    container_name: qilin-crm-daemon
    image: p1hub/qilin-crm-api:${TAG}
    restart: always
    depends_on:
      - crm-migration
    ports:
      - 8082:8080
    command: ["daemon","-c","configs/local.yaml","-b",":8080","-d"]
    environment:
      - APP_POSTGRES_DSN=postgres://qilin:insecure@postgres:5432/qilin?sslmode=disable
    networks:
      - default
  hasura:
    ports:
      - 8081:8080
    volumes:
      - ./../../assets/hasura/migrations:/hasura-migrations
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/qilin-hasura?sslmode=disable"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: insecure
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
  postgres:
    ports:
      - 5567:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  postgres: