version: '3.7'
services:
  qilin-crm-migrate:
    depends_on:
      - postgres
    restart: on-failure
    container_name: blueprint-migrate
    image: p1hub/qilin-crm-api:${TAG}
    command: ["migrate","up","--dsn","postgres://qilin:insecure@postgres:5432/qilin?sslmode=disable"]
    environment:
      - APP_TRACING_DISABLED=true
    networks:
      - default
  qilin-crm-daemon:
    depends_on:
      - qilin-crm-migrate
    container_name: qilin-crm-daemon
    image: p1hub/qilin-crm-api:${TAG}
    restart: always
    ports:
      - "8080:8080"
    command: ["daemon","-c","configs/local.yaml","-b",":8080","-d"]
    environment:
      - APP_POSTGRES_DSN=postgres://qilin:insecure@postgres:5432?sslmode=disable
    networks:
      - default
  postgres:
    container_name: qilin-postgres
    ports:
      - "5567:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  postgres: