version: '3.7'
services:
  crm-migration:
    command: ["migrate","up","--dsn","postgres://qilin:insecure@postgres:5432/qilin?sslmode=disable"]
  crm-daemon:
    container_name: qilin-crm-daemon
    image: p1hub/qilin-crm-api:${TAG}
    restart: always
    depends_on:
      - crm-migration
    ports:
      - 8082:8080
    command: ["daemon","-c","configs/local.yaml","-b",":8080","-d"]
    environment:
      - APP_POSTGRES_DSN=postgres://qilin:insecure@postgres:5432/qilin?sslmode=disable
    networks:
      - default
  hasura:
    ports:
      - 8081:8080
    volumes:
      - ./../../assets/hasura/migrations:/hasura-migrations
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/qilin-hasura?sslmode=disable"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: insecure
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      QILIN_CRM_ENDPOINT: "http://crm-daemon:8080/v1/graphql"
      QILIN_CRM_WEBHOOKS_ENDPOINT: "http://crm-daemon:8080/v1/webhooks"
      QILIN_CRM_WEBHOOKS_SECRET: "insecure"
      HASURA_GRAPHQL_JWT_SECRET: |
        {
          "type": "RS512",
          "key": "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1cGV3FeyHS6zzCfbS/G/\nWrpae9jdj7WozCUbIG5Yxg5Mnvxt+WkAHQloL2z13QX1FZ66pUvqa3c6ZPOn9KEi\nKgjQaHH84AwdpqMNK8adpmhfPYLOql0Kk28lJFlGhbZ8FSM1OHnyK2H2RikZGJv1\nJ5w9qMUFQIlKJGxSPbovwpMSzhcv6aG8PzGlz6K5Fhiy+CUGENuesmLfcpCM7mvr\nMJmDi6frGA4K3A6djCdUFoMtGtuA1v/a2c+EMvovG8FjEzynOxD1mnNJn9k77BwA\nABUqXnw2Rm+Usdmk+8wajVp3k4pdKM0kyuV5ttuoEIxzepVV1IpMIZ7XCx80awgw\nvyn+txj9QFtrP3iU4cKAuVYyvDD/50KlJgklGximGsNhFo4p5uOsM8DFsyXdCCRd\nx46p+4Hawj5LxqQObw0QVGAZbNe1S3cGcKvP4DA7J/n2e02/FgoXevHh9S7i4LpG\nekErTHOjsTaqMO+dpqpthxFPgq41hsppLOd9jwfMomFhDAhVpgfF9DKFfLdherR3\njov+4FBb3me3c7EdckNrEUUkhOKW2FbnLF/LLsPxgkJ0Tadr31oSocTqllAi+3eY\npgdTZOiAtSDePAujtv29LQW7p9NVOg3WsKULWlZRENnUBPdVWhFyTT3yl3jqICrr\nRSTGfW5nPesP6g4DPwP8/+MCAwEAAQ==\n-----END PUBLIC KEY-----",
          "issuer": "https://qilin.protocol.one",
          "claims_namespace": "https://qilin.protocol.one/claims"          
        }


  postgres:
    ports:
      - 5567:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  postgres: